const TASK_TYPES = ['PURCHASE', 'GENERAL'];

const EXECUTION_CREATION_ALLOWED_STATUSES = ['TODO', 'DONE', 'CANCELLED'];

const EXECUTION_UPDATE_ALLOWED_STATUSES = [
  'TODO',
  'DONE',
  'CANCELLED',
  'COVERED',
  'REFUNDED',
  'PARTIALLY_REFUNDED'
];

const DEFAULT_PURCHASE_QUANTITY_UNIT = 'piece';

module.exports = {
  TASK_TYPES,
  EXECUTION_CREATION_ALLOWED_STATUSES,
  EXECUTION_UPDATE_ALLOWED_STATUSES,
  DEFAULT_PURCHASE_QUANTITY_UNIT
};
